### ISSUE TITLE
Compact Ores causing world corruption

### ISSUE THREAD

**Issue by Nevrai** [DoubleNegation/CompactOres#31]
Whenever I try to leave my base and enter new chunks, the game server crashes. Nothing moves, TOP says “Waiting for server,” can’t type in chat or interact with anything, etc. The server is just dead. This always happens whenever I reach exactly the same point in the world after trying to get there several times after restarting my game, so I think it happens when I try to generate new chunks. I’m not sure why this is happening, but I’ve been generating new chunks underground just fine whilst mining before this. However, now, when I’m trying to explore the world a bit, my server is crashing, almost certainly because of Compact Ores judging from these errors in the log which appear a minute or two after the server has crashed.

This is in single-player. I have added a lot of compact ores, all of which are behaving and generating just fine after lots of testing. I have no clue why this world corruption issue is occurring.

Here is the error in the log. This same error is repeated several thousand times in the log.
<details>
  <summary>Error (click to expand)</summary>
  
```[00:39:01] [Worker-Main-3/ERROR]: Failed to light chunk [-160, -13]
java.util.concurrent.CompletionException: java.lang.StackOverflowError
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[client-1.18.2-20220404.173914-srg.jar%23403!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.18.2-20220404.173914-srg.jar%23403!/:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_6367_(ServerChunkCache.java:542) ~[client-1.18.2-20220404.173914-srg.jar%23403!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.18.2-20220404.173914-srg.jar%23403!/:?]
	at net.minecraft.server.level.ServerChunkCache$MainThreadExecutor.m_7245_(ServerChunkCache.java:550) ~[client-1.18.2-20220404.173914-srg.jar%23403!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[client-1.18.2-20220404.173914-srg.jar%23403!/:?]
	at net.minecraft.server.level.ServerChunkCache.getChunkBlocking(ServerChunkCache.java:1777) ~[client-1.18.2-20220404.173914-srg.jar%23403!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_7587_(ServerChunkCache.java:1673) ~[client-1.18.2-20220404.173914-srg.jar%23403!/:?]
	at net.minecraft.world.level.Level.m_6522_(Level.java:169) ~[client-1.18.2-20220404.173914-srg.jar%23403!/:?]
	at net.minecraft.world.level.Level.m_6325_(Level.java:3081) ~[client-1.18.2-20220404.173914-srg.jar%23403!/:?]
	at net.minecraft.world.level.Level.m_8055_(Level.java:3573) ~[client-1.18.2-20220404.173914-srg.jar%23403!/:?]
	at net.minecraft.world.level.Level.m_46717_(Level.java:868) ~[client-1.18.2-20220404.173914-srg.jar%23403!/:?]
	at net.minecraft.world.level.Level.m_46747_(Level.java:548) ~[client-1.18.2-20220404.173914-srg.jar%23403!/:?]
	at net.minecraft.world.level.block.state.BlockBehaviour.m_6810_(BlockBehaviour.java:148) ~[client-1.18.2-20220404.173914-srg.jar%23403!/:?]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60753_(BlockBehaviour.java:673) 
```
  
</details>

### Versions

* **Minecraft:** 1.18.2
* **Forge:** 40.1.80
* **Compact Ores:** 4.0.1 (latest)

**Comment by DeleteMetaInf** [comment]
Created a new world with the same seed. The same thing happens in exactly the same location as before. Other new chunks are generated fine, but when I go to this particular location, everything gets messed up and the game (server) freezes/crashes permanently until I restart the game, and when I try to go there again, the same thing occurs.

I’m getting these same errors repeated in my log: https://pastebin.com/raw/hH8M5iC1

And before that, I was getting these separate errors which I’m unsure whether are relevant, but they might be:
```
[02:35:19] [Server thread/WARN]: Tried to load a DUMMY block entity @ BlockPos{x=-449, y=-50, z=376} but found not block entity block Block{compactores:compactore__kubejs__deepslate_randomite_ore} at location
[02:35:19] [Server thread/WARN]: Tried to load a block entity for block Block{compactores:compactore__kubejs__deepslate_randomite_ore} but failed at location BlockPos{x=-449, y=-50, z=376}
```

**Comment by Nevrai** [comment]
Created a new world with the same seed. The same thing happens in exactly the same location as before. Other new chunks are generated fine, but when I go to this particular location, everything gets messed up and the game (server) freezes/crashes permanently until I restart the game, and when I try to go there again, the same thing occurs.

I’m getting these same errors repeated in my log: https://pastebin.com/raw/hH8M5iC1
“Failed to light chunk”
“java.util.concurrent.CompletionException: java.lang.StackOverflowError”

And before that, I was getting these separate errors which I’m unsure whether are relevant, but they might be:
```
[02:35:19] [Server thread/WARN]: Tried to load a DUMMY block entity @ BlockPos{x=-449, y=-50, z=376} but found not block entity block Block{compactores:compactore__kubejs__deepslate_randomite_ore} at location
[02:35:19] [Server thread/WARN]: Tried to load a block entity for block Block{compactores:compactore__kubejs__deepslate_randomite_ore} but failed at location BlockPos{x=-449, y=-50, z=376}
```

**Comment by Nevrai** [comment]
I hope you can look at this issue. I’d love to use this mod again, as it’s one of my favourites.
